version: '2'
services:
  web:
    logging:
      driver: "json-file"
      options:
        max-size: 256k
    stdin_open: true
    tty: true
    image: rails:latest
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - ../SCMI:/workspace
      - ./script:/script
    volumes_from:
      - box_web
    links:
      - redis_db
    ports:
      - 3000:3000
    command: sh -c 'cd /workspace && /script/start_rails'
  worker:
    logging:
      driver: "json-file"
      options:
        max-size: 256k
    stdin_open: true
    tty: true
    image: rails:latest
    environment:
      - BUNDLE_PATH=/bundle
    volumes:
      - ../SCMI:/workspace
      - ./script:/script
    volumes_from:
      - box_worker
    links:
      - redis_db
    command: sh -c 'cd /workspace && /script/start_worker'
  redis_db:
    logging:
      driver: "json-file"
      options:
        max-size: 256k
    image: redis:latest
    mem_limit: 128m
    ports:
      - 6379
    volumes:
      - ./database/redis:/data
  box_web:
    image: busybox
    volumes_from:
      - box_bundle_cache
    volumes:
      - /bundle
  box_worker:
    image: busybox
    volumes_from:
      - box_bundle_cache
    volumes:
      - /bundle
  box_bundle_cache:
    image: busybox
    volumes:
      - /bundle/cache
